### PR TITLE
Switch to using peerDependencies (fixes #4)

### LINKED ISSUE #4: Update dependencies in package.json to latest and add peerDependencies
```javascript
{
  "peerDependencies": {
    "mocha": ">=1.18 <3"
  },
  "dependencies": {
    "mocha": "^2.1.0"
  },
  "devDependencies": {
    "browserify": "^8.0.2",
    "chai": "^1.9.1",
    "eslint": "^0.11.0",
    "istanbul": "^0.3.2",
    "jsdoc": "^3.3.0-alpha9",
    "jsonlint": "^1.6.2",
    "mockery": "~1.4",
    "shelljs": "^0.3.0",
    "sinon": "^1.10.3"
  }
}

### PR DESCRIPTION
**Pull request by nzakas**
I tested this out on a couple of projects and everything worked correctly.

CR @j3tan @FredKSchott @mattwiller

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @nzakas has signed the CLA. Thanks for the pull request!

**Comment by nzakas** [comment]
Turns out we still need mocha as a dev dependency in order to run tests with our script.

**Comment by nzakas** [comment]
So yeah, we'll have both a peer dependency and a dev dependency going forward. Not the worst. :)

**Comment by FredKSchott** [comment]
:+1: This has to be very unique use-case for having both

**Pull request merged**
