### PR TITLE
updated package.json

### PR DESCRIPTION
**Pull request by EsrefDurna**
updated package istanbul from 0.3.2 to 0.4.5
 Npm link :  https://www.npmjs.com/package/istanbul
 Repository link : https://github.com/gotwarlost/istanbul/releases

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @EsrefDurna, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by EsrefDurna** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @EsrefDurna has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by EsrefDurna** [comment]
Thank you!

**Pull request merged**
